### PR TITLE
66-bug-fix-max-card-move-calculation

### LINKED ISSUE #66: [Bug]: Fix max card move calculation
**Describe the bug**
Currently we set max move size to 
`# of empty cells + # of empty tableaus + 1`.

This is incorrect. The calculation is a bit more complicated. Tableau piles should double the number of movable cards, except when it is the target of the move.

**Expected behavior**
`max move size = (# of empty cells + 1) * 2^(# of empty tableau piles that are not the target)`

### PR DESCRIPTION
**Pull request by jialincai**
## Description
Introduced more accurate formula for calculating max card move size in `Rule.ts`

Fixes #66

## Type of change
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/phasor/Rule.ts [hunk 1]
```diff
@@ -172,3 +165,23 @@ export function getUpdatedCardPlacements(
...
 }
+
+/**
+ * Calculates the maximum number of cards that can be moved in a single stack.
+ * Based on Freecell-style rules: (empty cells + 1) * 2^(empty tableaus excluding the target).
+ *
+ * @param deck - The current deck state
+ * @param targetPileId - The pile the stack will be dropped on. If PileId.None, all tableau piles are considered.
+ */
+function _getMaxMovableStackSize(deck: Deck, targetPileId: PileId): number {
```
Comment (jialincai) [inline src/phasor/Rule.ts:176]: New function to calculate max move size.

File: src/phasor/Rule.ts [hunk 2]
```diff
@@ -93,15 +93,8 @@ const DRAG_RULES: Record<PileId, (deck: Deck, card: Card) => boolean> =
...
-        const maxMoveSize = [...TABLEAU_PILES, ...CELL_PILES].reduce(
-          (accum, pileId) => {
-            return accum + Number(deck.pileChildren(pileId).length === 0);
-          },
-          1,
-        );
-
         return (
-          dragChildren.length <= maxMoveSize &&
+          dragChildren.length <= _getMaxMovableStackSize(deck, PileId.None) &&
```
Comment (jialincai) [inline src/phasor/Rule.ts:97]: When determining valid drag we make the optimistic assumption that player will not drag the stack into an empty tableau pile.

File: src/phasor/Rule.ts [hunk 3]
```diff
@@ -49,16 +49,16 @@ const DROP_RULES: Record<PileId, (deck: Deck, card: Card) => boolean> =
...
-        const pileAfterDrop = [
-          ...deck.pileChildren(pileId),
-          ...deck.cardChildren(card),
-        ];
-        const activeSequence = pileAfterDrop.slice(
-          -deck.cardChildren(card).length - 1,
-        );
+        const dragChildren = deck.cardChildren(card);
+        if (dragChildren.length > _getMaxMovableStackSize(deck, pileId))
+          return false;
```
Comment (jialincai) [inline src/phasor/Rule.ts:58]: When determining valid drop we make require strict adherence to max drop size formula.
