### PR TITLE
57-bug-dragging-allowed-after-snapping

### LINKED ISSUE #57: [Bug]: Dragging allowed after snapping
**Describe the bug**
After snapping to a foundation pile, cards can still be drug. The motion is disorienting.

**To Reproduce**
1. Click down on a card that can snap to a foundation pile (don't let go)
2. Drag in any direction.

**Expected behavior**
After snapping to a foundation pile, a card should no longer be able to moved.

### PR DESCRIPTION
**Pull request by jialincai**
## Description
- Additional drag rules which should prevent any card in the foundation pile from being drug.
- Added `Validation.ts` which helps perform checks such as `hasSameSuit` or `isAscendingOrder` on card sequence arrays.
- Added `pileChildren` which deprecates finicky `Deck` functions. (All uses has been updated)

Fixes #57 

## Type of change
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/phasor/Validation.ts
Comment (jialincai) [inline src/phasor/Validation.ts:1]: Introduce new functions to check certain attributes about a sequence of cards.

File: src/phasor/Rules.ts [hunk 1]
```diff
@@ -3,36 +3,62 @@ import Card from "./Card";
...
-                child.value === prevCard.value - 1 // Must be in descending order.
-            );
-        });
+        const maxMoveSize = [...TABLEAU_PILES, ...CELL_PILES].reduce((accum, pileId) => {
+            return accum + Number(deck.pileChildren(pileId).length === 0);
+        }, 1);
+
+        return dragChildren.length <= maxMoveSize && isValidSequence(dragChildren, [hasAlternatingColor, isDescendingOrder]);
     }])
 ]);
```
Comment (jialincai) [inline src/phasor/Rules.ts:63]: Define drag rules. These rules specify weather or not a card should be allowed to move on drag start.

File: src/phasor/Rules.ts [hunk 2]
```diff
@@ -3,36 +3,62 @@ import Card from "./Card";
...
-    
+
     // Tableau piles: Cards must alternate in color and be placed in descending order.
     ...TABLEAU_PILES.map(pileId => [pileId, (deck: Deck, card: Card) => {
-        const topCard = deck.topCard(pileId);
+        const pileAfterDrop = [...deck.pileChildren(pileId), ...deck.cardChildren(card)];
+        const activeSequence = pileAfterDrop.slice(-deck.cardChildren(card).length - 1);
+        return isValidSequence(activeSequence, [hasAlternatingColor, isDescendingOrder]);
+    }])
+]);
```
Comment (jialincai) [inline src/phasor/Rules.ts:38]: We use the sequence attribute checks is `Validation.ts` here to simplify logic.

File: src/phasor/Deck.ts [hunk 3]
```diff
@@ -53,60 +53,27 @@ export default class Deck {
...
-      }
-
-      if (SUIT_COLOR[current.suit] === SUIT_COLOR[previous.suit])
-      {
-        return false;
-      }
-    }
-
-    return true;
-  }
```
Comment (jialincai) [inline src/phasor/Deck.ts:95]: I feel this function is awkwardly placed and too inflexible. Replace with `DRAG_RULES` in `Rules.ts`.

File: src/phasor/Deck.ts [hunk 4]
```diff
@@ -53,60 +53,27 @@ export default class Deck {
...
-      0
+  /**
+   * Returns the given card and all following cards in the same pile.
+   *
+   * @param {Card} card - The reference card.
+   * @returns {Card[]} Cards in the same pile, sorted by ascending position.
+   */
+  public cardChildren(card: Card): Card[] {
+    return this.pileChildren(card.pile).filter(
+      (curr: Card) => curr.position >= card.position
```
Comment (jialincai) [inline src/phasor/Deck.ts:76]: `topCards` and `countCards` have been deprecated.

Please use `pileChidren` instead of achieve these aims.

`cardChildren` simply further filters the output of `pileChildren`.
