### PR TITLE
58-bug-max-card-move-is-not-enforced

### LINKED ISSUE #58: [Bug]: Max card move is not enforced
**Describe the bug**
We are able to move chains of ANY length. The drag motion isn't activated but the cards can still be dropped.

**To Reproduce**
1. Create a long chain, one that cannot be moved in a single step.
2. Click and drag the chain to a valid position (barring the fact that the chain is too long).

**Expected behavior**
If a chain is too long to be moved in a one step. It shouldn't be allowed to move.

**Additional Context**
I think this error has something to do with drops happening even if drag rules were invalid.
There's another bug that's caused by the same error: Cards can be dragged from foundation pile back to tableau or cells.

### PR DESCRIPTION
**Pull request by jialincai**
## Description
Added `canMoveCard` to every input listener handler.

Fixes #58 

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/phasor/GameState.ts [hunk 1]
```diff
@@ -30,8 +30,6 @@ export default class GameState extends Phaser.Scene {
 
   private score: number = 0;
 
-  private dragChildren: Card[] = [];
```
Comment (jialincai) [inline src/phasor/GameState.ts:33]: All use of global variable `dragChildren` is removed.

User should use `cardChildren` to get the drag children associated with the GameObject(card) being drug.

File: src/phasor/GameState.ts [hunk 2]
```diff
@@ -115,7 +110,11 @@ export default class GameState extends Phaser.Scene {
         gameObject: Phaser.GameObjects.GameObject,
         dropZone: Phaser.GameObjects.GameObject,
       ) => {
-        if (gameObject instanceof Card && dropZone instanceof Pile) {
+        if (
+          gameObject instanceof Card &&
+          dropZone instanceof Pile &&
+          canMoveCard(this.deck, gameObject)
```
Comment (jialincai) [inline src/phasor/GameState.ts:116]: We add `canMoveCard` to every event.

In the future we may explore more DRY way to check `gameObject instanceof Card && canMoveCard(this.deck, gameObject)` before every event.
