### PR TITLE
42 bug only kings can be placed into open tableaus

### LINKED ISSUE #42: [Bug]: Only kings can be placed into open tableaus
**Describe the bug**
Only kings can be placed into an open tableau pile. 

**To Reproduce**
1. Try to place a card other than a king in an open tableau pile.

**Expected behavior**
Any card should be able to be placed in an open tableau pile.

### PR DESCRIPTION
**Pull request by jialincai**
## Description
We've moved dropping related game logic into `src/phasor/Rules.ts`.

Additionally auto snap to foundation pile functionality has been rolled back. We will re-tackle in separate issue.

Due to drop rules clarification, any card can be dropped in empty tableau deck.

Fixes #42 

## Type of change
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:
- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/phasor/GameState.ts [hunk 1]
```diff
@@ -107,7 +108,7 @@ export default class GameState extends Phaser.Scene {
         gameObject: Phaser.GameObjects.GameObject,
         dropZone: Phaser.GameObjects.GameObject
       ) => {
-        if (gameObject instanceof Card) {
+        if (gameObject instanceof Card && dropZone instanceof Pile) {
```
Comment (jialincai) [inline src/phasor/GameState.ts:111]: Limits drops to—specifically—dropping a card into a pile.

File: src/phasor/GameState.ts [hunk 2]
```diff
@@ -130,19 +131,18 @@ export default class GameState extends Phaser.Scene {
...
+    //   (
+    //     _pointer: Phaser.Input.Pointer,
+    //     gameObject: Phaser.GameObjects.GameObject
+    //   ) => {
+    //     if (gameObject instanceof Card) {
+    //       this.pointerUpCard(gameObject);
+    //     }
+    //   },
+    //   this
+    // );
```
Comment (jialincai) [inline src/phasor/GameState.ts:145]: `pointerUpCard` requires a boolean to be returned from `dropCard` and introduces a new global variable. I think this is overly entangled so we're commenting out this functionality and will re-tackle in a separate issue.

File: src/phasor/GameState.ts [hunk 3]
```diff
@@ -249,98 +249,49 @@ export default class GameState extends Phaser.Scene {
...
-
-    // Flip top card on past stack
-    const topCardNew = this.deck.topCard(oldCardPile);
-    if (topCardNew && topCardNew !== card && !topCardNew.flipped) {
-      topCardNew.flip(this);
-      this.flipScore(topCardNew.pile);
-    }
-
-    return dropped;
-  }
```
Comment (jialincai) [inline src/phasor/GameState.ts:314]: `dropCard` return `void` to stay consistent with other input listener functions.

All dropping related game logic has been extracted into `src/phasor/Rules.ts`.

**Comment by jialincai** [comment]
### Results
Moved 4-3 to left-most tableau successfully.
Screenshot 2025-03-14 at 2 44 13 PM
